# Gibbs Sampler for Bayesian GMM 

### The Target Distribution
Recall that in our model, we suppose that our data, $\mathbf{X}=\{\mathbf{x}_1, \ldots, \mathbf{x}_N\}$ is drawn from the mixture of $K$ number of Gaussian distributions. For each observation $\mathbf{x}_n$ we have a latent variable $\mathbf{z}_n$ that is a 1-of-$K$ binary vector with elements $z_{nk}$. We denote the set of latent variable by $\mathbf{Z}$. Recall that the distibution of $\mathbf{Z}$ given the mixing coefficients, $\pi$, is given by
\begin{align}
p(\mathbf{Z} | \pi) = \prod_{n=1}^N \prod_{k=1}^K \pi_k^{z_{nk}} 
\end{align}
Recall also that the likelihood of the data is given by,
\begin{align}
p(\mathbf{X} | \mathbf{Z}, \mu, \Sigma) =\prod_{n=1}^N \prod_{k=1}^K \mathcal{N}\left(\mathbf{x}_n| \mu_k, \Sigma_k\right)^{z_{nk}}
\end{align}
Finally, in our basic model, we choose a Dirichlet prior for $\pi$ 
\begin{align}
p(\pi) = \mathrm{Dir}(\pi | \alpha_0) = C(\alpha_0) \prod_{k=1}^K \pi_k^{\alpha_0 -1},
\end{align}
where $C(\alpha_0)$ is the normalizing constant for the Dirichlet distribution. We also choose a Normal-Inverse-Wishart prior for the mean and the covariance of the likelihood function
\begin{align}
p(\mu, \Sigma) = p(\mu | \Sigma) p(\Sigma) = \prod_{k=1}^K \mathcal{N}\left(\mu_k | \mathbf{m}_0, \mathbf{V}_0\right) IW(\Sigma_k|\mathbf{S}_0, \nu_0).
\end{align}
Thus, the joint distribution of all the random variable is given by
\begin{align}
p(\mathbf{Z}, \pi, \mu, \Sigma | \mathbf{X}) = p(\mathbf{X} | \mathbf{Z}, \mu, \Sigma) p(\mathbf{Z} | \pi) p(\pi) p(\mu | \Sigma) p(\Sigma)
\end{align}

### Gibbs Samper
The full conditionals are as follows:
1. $p(\mathbf{z}_{n} = \delta(k) | \mathbf{x}_n, \mu, \Sigma, \pi)  \propto \pi_k \mathcal{N}(\mathbf{x}_n | \mu_k, \Sigma_k)$.
2. $p(\pi|\mathbf{Z}) = \mathrm{Dir}(\{ \alpha_k + \sum_{i=1}^N \mathbb{I}(\mathbf{z}_{n} = \delta(k))\}_{k=1}^K)$
3. $p(\mu_k | \Sigma_k, \mathbf{Z}, \mathbf{X}) = \mathcal{N}(\mu_k | m_k, V_k)$
4. $\mathbf{V}_k^{-1} = \mathbf{V}_0^{-1} + N_k\Sigma_k^{-1}$
5. $\mathbf{m}_k = \mathbf{V}_k(\Sigma_k^{-1}N_k\overline{\mathbf{x}}_k + \mathbf{V}_0^{-1}\mathbf{m}_0)$
6. $N_k = \sum_{n=1}^N \mathbb{I}(\mathbf{z}_{n} = \delta(k))$
7. $\overline{\mathbf{x}}_k = \displaystyle \frac{\sum_{n=1}^N \mathbb{I}(\mathbf{z}_{n} = \delta(k))\mathbf{x}_n}{N_k}$
8. $p(\Sigma_k | \mu_k, \mathbf{z}, \mathbf{x}) = IW(\Sigma_k | \mathbf{S}_k, \nu_k)$
9. $\mathbf{S}_k = \mathbf{S}_0 + \sum_{n=1}^N \mathbb{I}(\mathbf{z}_{n} = \delta(k))(\mathbf{x}_n - \mu_k)(\mathbf{x}_n - \mu_k)^\top$
10. $\nu_k = \nu_0 + N_k$

The algorithm for the sampler is as follows:
1. Instantiate the latent variables randomly.
2. For $k=1...K$:
    3. For $n=1...N$: update $z_i$ by sampling from $p(\mathbf{z}_{n} = \delta(k) | \mathbf{x}_n, \mu, \Sigma, \pi)$.
    4. Update $\pi$
    5. Update variables for each component 

In [3]:
import numpy as np
import scipy.stats

In [4]:
N = 10
K = 3
dimensions = 4
mu = np.random.uniform(0,1,[N,K])
# Sigma = np.random.uniform(0,1,[N,K])
# X = np.random.uniform(0,1,[N,dimensions])
# scipy.stats.norm(mu, Sigma).pdf(X)
mu

array([[ 0.68276335,  0.04153166,  0.82237552],
       [ 0.81003542,  0.67225182,  0.03770043],
       [ 0.29673968,  0.53954806,  0.56597002],
       [ 0.81821523,  0.9556991 ,  0.83974211],
       [ 0.64051746,  0.1884108 ,  0.69722839],
       [ 0.46902524,  0.39094551,  0.85628296],
       [ 0.44434655,  0.02226147,  0.41945852],
       [ 0.3543623 ,  0.93396813,  0.14651943],
       [ 0.82850378,  0.84815628,  0.59560089],
       [ 0.85452344,  0.67944386,  0.56578022]])

In [5]:
np.sum(mu, axis=0)

array([ 6.19903245,  5.27221668,  5.5466585 ])

In [ ]:
# It would be easier to debug if we implement each update separately
def update_Z(delta_k, X, mu, Sigma, pi):
    Z = pi * scipy.stats.norm(mu, Sigma).pdf(X)
    
    return Z

def update_pi(alpha_k, Z):
    pi = np.random.dirichlet()m
    return pi

def update_mu_k(m_k, V_k):
    return mu_k

def update_V_k(N_k, Sigma_k):
    return V_k

def update_m_k(V_k, Sigma_k, N_k, mean_x_k, V_0, m_0):
    return m_k

def update_N_k(Z):
    return N_k

def update_mean_x_k(Z, X, N_k):
    return mean_x_k

def update_Sigma_k(S_k, nu_k):
    return Sigma_k

def update_S_k(S_0, Z, X, mu_k):
    return S_k

def update_nu_k(nu_0, N_k):
    return nu_k

# this function can be reused even when we change the prior on pi 
def gibbs_gmm(K, X, nu_0, S_0, V_0, m_0, alpha_0):
    return samples

In [17]:
a = [[1,2,3],[4,5,6]]
np.tile(a,(3,1))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [16]:
a

[[1, 2, 3], [4, 5, 6]]